import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Email forms in next.js",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex gap-6 flex-wrap items-center justify-center p-10">
          <Link 
                className="flex items-center gap-2 hover:underline hover:underline-offset-4" 
                href="/"
            > 
            <Image
                aria-hidden
                src="/home.svg"
                alt="Home icon"
                width={16}
                height={16}
              />
            home
          </Link> 
          <Link 
                className="flex items-center gap-2 hover:underline hover:underline-offset-4" 
                href="/emailform"
            > 
            <Image
                aria-hidden
                src="/file.svg"
                alt="File icon"
                width={16}
                height={16}
              />
            go to email form
          </Link>  
          <Link 
                className="flex items-center gap-2 hover:underline hover:underline-offset-4" 
                href="/about"
            > 
            <Image
                aria-hidden
                src="/window.svg"
                alt="Window icon"
                width={16}
                height={16}
              />
            about
          </Link>  
        </header>
        {children}
      </body>
    </html>
  );
}
